package com.github.advent

import scala.Console.println

object Day02b {

  def main(args: Array[String]): Unit = {
    println("day02...")
    var lines = data.split('\n').toList
    var games = parse( lines, List() )
    Console.println(games)

    var as = games.map(adjust(_))

    var ss = as.map( score(_) )
    Console.println(ss)
    Console.println(ss.sum)
  }

  def parse( lines : List[String], accum : List[(Char,Char)] ) : List[(Char,Char)] = {

    if lines.isEmpty  then
      accum
    else
      var cs = lines.head.trim.split(' ')
      parse( lines.tail, accum :+ (cs(0)(0),cs(1)(0)) )
  }

  def adjust( round : (Char,Char) ) : (Char,Char) = {

    round._2 match {
      case 'X' => {
        round._1 match {
          case 'A' => ('A','Z')
          case 'B' => ('B','X')
          case 'C' => ('C','Y')
        }
      }
      case 'Y' => {
        round._1 match {
          case 'A' => ('A','X')
          case 'B' => ('B','Y')
          case 'C' => ('C','Z')
        }
      }
      case 'Z' => {
        round._1 match {
          case 'A' => ('A', 'Y')
          case 'B' => ('B', 'Z')
          case 'C' => ('C', 'X')
        }
      }
    }
  }

  def score( round : (Char,Char) ) : Int = {

    round._2 match {
      case 'X' => 1 + winner(round._1,round._2)
      case 'Y' => 2 + winner(round._1,round._2)
      case 'Z' => 3 + winner(round._1,round._2)
    }

  }


  def winner( c1 : Char, c2 : Char ) : Int = {

    c1 match {
      case 'A' => {
        c2 match {
          case 'X' => 3
          case 'Y' => 6
          case 'Z' => 0
        }
      }
      case 'B' => {
        c2 match {
          case 'X' => 0
          case 'Y' => 3
          case 'Z' => 6
        }
      }
      case 'C' => {
        c2 match {
          case 'X' => 6
          case 'Y' => 0
          case 'Z' => 3
        }
      }
    }

  }


  var test = """A Y
               B X
               C Z"""
  
  var data = """C Y
               C Z
               B Z
               A Z
               A Z
               A Y
               A Z
               C Y
               C Z
               A Y
               A Y
               B X
               A Y
               C Z
               C Z
               B X
               C Z
               A Z
               B Y
               C Z
               A Y
               C X
               B Y
               A Z
               B Y
               C Z
               B Z
               B Y
               C Z
               A Z
               A Z
               B Z
               C Z
               A X
               B X
               C Y
               C Z
               C Z
               C Z
               A Y
               C Z
               C Z
               C Z
               C X
               A Z
               A Z
               C Y
               A Z
               C Z
               C Z
               C Z
               A Z
               B Y
               C Z
               A Z
               B Z
               A Z
               A Y
               B X
               B X
               C Z
               C X
               C Z
               C Z
               A Z
               B Z
               B X
               B X
               B Y
               C X
               C Y
               A Y
               C Z
               A Y
               C Z
               A X
               B X
               B X
               C X
               B X
               B X
               A Y
               B Y
               C Y
               A Z
               C Y
               B Y
               B X
               B X
               B Z
               B X
               B Z
               A Z
               B Y
               C Z
               B Z
               B Z
               B Y
               A Y
               C Z
               A Z
               C Y
               C Z
               B Z
               C Z
               C Z
               B Y
               A Z
               C Z
               C Z
               A Z
               A Z
               B X
               C Y
               A Y
               C Z
               B Y
               C Z
               A Y
               C X
               C X
               B Y
               C Z
               C X
               C Z
               B Y
               A Y
               B Z
               C Z
               B Y
               C Y
               C Z
               C Z
               B Z
               C Z
               A Z
               A Y
               C Z
               C Z
               B Y
               A Z
               C Z
               C Z
               C Y
               B Y
               C Z
               C Z
               C Z
               C Z
               A X
               B Y
               C Z
               B Y
               C Z
               B Y
               C X
               C Y
               A X
               C Z
               B X
               B X
               A Z
               A Z
               A Z
               B Y
               C Z
               B Z
               A Z
               B Y
               C Y
               C Z
               C Z
               C Z
               C Y
               C Z
               B Y
               C Z
               C Z
               B Z
               A Y
               B Z
               C Z
               C Y
               A Z
               C X
               B Z
               C Y
               B Y
               C Z
               C Z
               A Z
               C Y
               C Y
               C Y
               B Y
               C Z
               C X
               B Y
               C Z
               C Y
               B Z
               A Y
               C Z
               A Y
               B Z
               A Y
               A Y
               B Z
               A Z
               C Z
               C Z
               B X
               C Z
               C Z
               B X
               B Y
               C Z
               C X
               A X
               C Z
               C Z
               C Z
               B X
               B X
               A Z
               C Z
               C X
               A Z
               C Z
               C Z
               A Z
               B Z
               C Z
               B Y
               C Z
               A Y
               B Z
               C Z
               C Z
               C Z
               C X
               A X
               A Y
               B Y
               C Z
               B Y
               C X
               A Y
               C Z
               C Z
               B Y
               B Z
               C Z
               B Y
               B Y
               B Y
               A Y
               C Z
               B Z
               A X
               B Y
               C Z
               C Z
               C X
               A Y
               C Z
               A X
               B Y
               A X
               A Z
               B X
               B X
               C Z
               C Z
               A X
               C Z
               A Y
               B Y
               B Z
               C X
               C Y
               B X
               C Z
               C Y
               B Y
               C Z
               C X
               B Z
               C Z
               C Z
               C X
               C Y
               C Z
               A Y
               C Z
               C Z
               C Z
               C Z
               C Z
               C Y
               B Y
               C Z
               A X
               A Z
               C Y
               B Z
               B X
               A Z
               C Z
               C Y
               C Z
               C X
               A Y
               C Z
               A Z
               B Y
               B Z
               C Z
               B Z
               A Y
               C Z
               B Y
               C Z
               C Y
               C Z
               C X
               A Y
               A Y
               C Y
               C Z
               C Z
               B Y
               A Z
               C Z
               C Y
               A Y
               A Z
               A Z
               C X
               C Z
               B X
               C Y
               C Z
               C Z
               B Y
               C Z
               B X
               C Z
               B Z
               B Y
               C X
               C X
               A X
               B Y
               A Z
               C X
               B X
               A Z
               C Z
               C Z
               A X
               A Y
               B X
               C Z
               A X
               C Z
               B Y
               C Z
               A Y
               B Y
               C Z
               B Z
               B Y
               A Z
               C Z
               A X
               B Z
               C Y
               B Z
               B Y
               A Z
               A Y
               A Z
               A X
               C X
               A X
               C Y
               C Z
               A Y
               C Y
               B X
               A X
               A Y
               C Y
               B Y
               C Z
               C Z
               B Z
               C Z
               C Z
               C Z
               C Z
               C Z
               C Z
               C Z
               B Y
               C Z
               A Y
               B Y
               C Y
               C X
               C Z
               B Z
               B Y
               C Y
               C Z
               A Z
               C Y
               B Z
               C Z
               A Z
               C X
               B Y
               B Y
               B Y
               C Z
               B Y
               A Y
               C Z
               C Z
               A Z
               A Z
               C Z
               B Z
               B Y
               C Z
               B Y
               B Z
               C Z
               A X
               A X
               C X
               C Y
               A Y
               C Z
               A Y
               A Z
               C Z
               C Z
               C Z
               B Y
               A Z
               B Z
               C X
               B X
               C X
               B Y
               C Z
               A Z
               C Z
               A X
               B Z
               B Z
               B Y
               A Y
               C Z
               B X
               C Z
               B Z
               C X
               A X
               C Z
               C Z
               B Z
               B Y
               C Z
               C Z
               A Z
               C Y
               C Z
               B Y
               A Y
               B Y
               A Y
               C Z
               C Y
               B Z
               A Y
               C Z
               B X
               B X
               B X
               C Y
               C Z
               A Y
               C Z
               C Z
               C Z
               A Y
               C Z
               B X
               A Z
               C Z
               C Z
               A Y
               C Z
               C Z
               B X
               C Z
               B Y
               A Z
               C X
               C Y
               C Y
               C Z
               C Y
               A Y
               B Z
               C Z
               C Z
               C Z
               B Y
               C Z
               C Z
               A Y
               A X
               A Y
               C Y
               C Z
               C Z
               A X
               B Z
               C Z
               C Z
               B Z
               B Y
               C Z
               A X
               C X
               A Z
               B Z
               C Z
               A X
               C X
               C Z
               B Y
               A X
               A X
               C Z
               C Z
               B X
               C Z
               B Z
               B Y
               A X
               C Y
               C Z
               C X
               A Y
               B Y
               C Z
               C Z
               C Z
               C Z
               B Z
               A Y
               C Z
               C Z
               B Z
               C Y
               B Z
               B X
               B Y
               A Z
               C Z
               A Z
               B Y
               C Y
               C Z
               C Z
               C Z
               B Z
               C Z
               C X
               C Z
               B X
               C Y
               B Y
               C Z
               C Z
               C Z
               C Z
               B Y
               B Y
               C Z
               B Y
               C X
               B Z
               A X
               C X
               C Z
               B X
               C Z
               C X
               C Z
               A X
               A Z
               B X
               C Z
               C Z
               B Y
               C Z
               A Y
               C Z
               C Z
               C Y
               C Z
               A Z
               A X
               C X
               B Y
               A Y
               B Y
               A X
               C Z
               B Y
               B Y
               C Z
               C Z
               B Y
               B X
               A Y
               C Z
               B Y
               C Y
               C Z
               C Z
               C X
               B Y
               A Z
               C Z
               A Z
               A X
               C X
               A Z
               C Z
               C Z
               A X
               B Z
               C Z
               B Y
               A Z
               A Y
               A X
               A Y
               A X
               C Z
               A X
               B Y
               A Y
               B Z
               C Y
               C Z
               B Z
               C X
               A Y
               A Y
               C Z
               C Y
               C Z
               B Y
               B Y
               B Y
               B X
               C Z
               C X
               B Y
               C Z
               C Z
               B Y
               C Z
               C Z
               B Y
               C Z
               C Y
               C Z
               C Y
               C Z
               C Y
               A Y
               A Y
               C Y
               C Y
               C Y
               C Y
               C Z
               C X
               B Z
               B Z
               C X
               C Z
               B Y
               B Y
               A Z
               C Y
               C Z
               C Z
               C X
               C Z
               C Z
               A Z
               B Y
               C Z
               A Y
               C Z
               C Z
               C Z
               A Z
               C X
               C Y
               B Y
               A Z
               B Z
               C Z
               B Y
               C Z
               B Z
               C X
               A X
               C Y
               A Y
               B Z
               B Y
               A X
               C Z
               B Z
               C Z
               C Z
               C X
               B Z
               C X
               A Z
               B Z
               C Z
               C Z
               C Z
               B Y
               A X
               C Z
               C Y
               C Y
               C Z
               A Z
               C Z
               C Z
               A X
               C Y
               B Y
               A Y
               A Z
               A Z
               B Z
               C Z
               A Z
               B Y
               B Y
               A Y
               A Z
               A Z
               C Z
               C Z
               C Z
               A X
               C Z
               B Z
               B X
               C Y
               A Z
               B Y
               C Z
               B Y
               A X
               C Z
               A Z
               C Z
               B Z
               C Y
               C Z
               B Y
               A Z
               B Z
               A Y
               B X
               C Z
               B Y
               C Z
               C Z
               C X
               C Y
               C Z
               B X
               C X
               A Y
               A Y
               C Z
               C Y
               B Y
               C Y
               C Y
               C Z
               A Y
               A Z
               B Y
               C Z
               C Z
               A X
               C Z
               C Y
               C Z
               B X
               C Y
               A Z
               A Y
               A Z
               C X
               C Z
               C Z
               C Z
               B Z
               C Y
               B Z
               C Z
               B Y
               C Z
               B Y
               A Y
               B X
               C Z
               A Y
               C Z
               A Y
               A Z
               A Z
               B Z
               A Y
               C Z
               A X
               B Y
               C Z
               B Z
               C Z
               A Y
               A Y
               B Z
               B X
               B X
               C Y
               C Z
               C Z
               C Y
               A X
               B Z
               C X
               B Y
               C X
               B X
               C X
               C X
               C Z
               A Y
               C Y
               C Z
               B Z
               A Z
               A Z
               C Z
               A Z
               C Z
               A Z
               A X
               B Y
               A X
               A Y
               C X
               B Y
               C Z
               A X
               B X
               C Z
               C Z
               C X
               B X
               A Z
               B X
               C Z
               B Y
               C Z
               C X
               C Z
               C X
               C Z
               B Z
               B Y
               C Z
               B X
               C X
               C Z
               C Y
               A Z
               B Z
               A X
               B X
               B X
               C Z
               B Z
               C X
               A Y
               C Z
               C Z
               B Y
               C X
               C Z
               A X
               B Y
               C Z
               C Z
               C Z
               C Z
               C Z
               A X
               A Z
               C X
               A Z
               C Z
               A Z
               C Z
               B Y
               B Z
               A X
               C X
               C Z
               B Z
               A Z
               C Z
               C Y
               C Z
               C Z
               C X
               A Y
               B Y
               C Z
               A Y
               C Z
               B Z
               C X
               B Z
               B Z
               B X
               B Z
               C Y
               C Z
               C Y
               B Y
               C Y
               C Z
               C X
               C X
               A Z
               B Y
               C Z
               A Y
               B X
               C Y
               A Y
               A Z
               B Y
               B Y
               A Y
               B Y
               B Z
               A X
               C Z
               B Y
               A X
               C Z
               C Z
               C X
               B Y
               A Z
               A X
               B Y
               A Z
               C Z
               B Z
               B Z
               B Y
               B Y
               A Z
               A Z
               A Y
               C Z
               C Z
               A Z
               C Z
               C Z
               C Z
               A X
               C Z
               A Y
               C Y
               A Z
               C Z
               B Y
               C X
               B Y
               C Z
               C Z
               C Z
               A Z
               B Z
               B X
               C Z
               C Z
               A Y
               B Z
               B X
               C Z
               C Y
               A Y
               C Y
               C Y
               C Z
               C Y
               C X
               C Y
               B Z
               B Y
               C Z
               A Z
               A Y
               C Z
               C Z
               B Y
               B Y
               A Z
               A Z
               A X
               C Z
               C Z
               A Y
               B Y
               C X
               C Z
               C Z
               A Z
               C Z
               B X
               B Y
               A Y
               C Z
               A X
               A Y
               C Z
               B X
               C X
               B Z
               C Y
               C X
               B Y
               B Y
               C Z
               C Z
               C X
               C Z
               A Y
               A Z
               C Y
               C Z
               A Z
               C Z
               C Y
               A X
               C X
               C Z
               B X
               C Z
               B X
               C Z
               C Z
               C Z
               B X
               B Y
               B Y
               B Y
               C X
               B Y
               C Z
               C Y
               C Z
               C Z
               B X
               C Y
               B Z
               C Z
               C Y
               C X
               C Z
               A X
               A Z
               C Z
               C Y
               C X
               C Z
               B Y
               C X
               C Y
               C Z
               C X
               A Z
               B Y
               B X
               C X
               C Y
               B Z
               C Z
               C Y
               B Z
               C X
               A Z
               A Y
               C Z
               C Z
               C X
               B Y
               C Y
               C Z
               A Z
               B Z
               B Y
               B Y
               B Z
               C Z
               A X
               B Y
               A Z
               A Y
               C Z
               C Z
               B Y
               C Y
               C Z
               B Z
               A Z
               B Z
               C Z
               C Z
               B Y
               B X
               C Z
               C Y
               C Z
               A Y
               C Z
               A X
               C X
               B Y
               B X
               C X
               C Z
               C X
               B Z
               C Z
               A Z
               B Z
               C Z
               A X
               C Z
               C Z
               A Y
               B Y
               B Z
               B X
               B Z
               C X
               B Y
               C Z
               C Z
               C Z
               A Z
               C Z
               C X
               C X
               B Y
               C X
               C X
               C Z
               C Z
               A Z
               C Y
               C Z
               C Z
               B Z
               C Z
               A Y
               B Y
               C Z
               C Z
               B Y
               B Y
               C X
               C Z
               B X
               A Y
               B Z
               A Y
               A Y
               A Y
               C Y
               C Y
               C Z
               B X
               B Z
               C Z
               C X
               C X
               B Z
               A Z
               A X
               B Y
               C Z
               B Z
               A Z
               B X
               C Z
               A Y
               C Z
               A Z
               A Z
               C Z
               C X
               C Z
               C Y
               A X
               B Y
               C Z
               C Z
               C Z
               C Z
               C Z
               A Y
               C X
               C Z
               A Y
               B X
               C Z
               A Y
               C Z
               C Z
               C Y
               B Z
               B X
               C Z
               A X
               B Y
               C Z
               C Z
               A X
               A Y
               C Z
               C Y
               B Y
               C Z
               C Z
               A Y
               A Y
               A Y
               A Y
               C Z
               A X
               A Z
               B Y
               B Z
               A Z
               C Y
               C Z
               C Z
               C Z
               A Z
               C Z
               A Z
               C Z
               C Z
               A Z
               C Z
               C Z
               A Z
               B X
               C Z
               A Y
               B Y
               C Z
               A X
               C Z
               A Y
               C Z
               C Z
               C Y
               C Z
               A X
               B Y
               C Z
               A Z
               C Z
               A Z
               A Z
               B Y
               C X
               B Y
               C X
               C X
               C Z
               A Y
               B Z
               A Y
               C Z
               C Z
               B Z
               A Y
               C Z
               B Y
               C Z
               A X
               C Z
               C Z
               C Z
               B Z
               A X
               B Y
               C Z
               A X
               C Z
               C X
               B Y
               C Z
               A Y
               C Y
               B Y
               A Y
               C Z
               A X
               B Y
               A Y
               A Z
               C Z
               C Z
               C X
               A Z
               C Z
               C Z
               B Y
               B X
               A Z
               C Z
               B X
               C Z
               C Y
               C Z
               C Z
               C Z
               C Y
               A Y
               C Z
               C Y
               C Z
               C Z
               B Y
               B Y
               B X
               C Y
               B Z
               C Z
               B Y
               C Z
               C Z
               C Z
               A Z
               A Y
               C Y
               C Z
               C Z
               A Z
               C Z
               C Z
               C Z
               B Y
               B X
               B Y
               A Y
               C Z
               B Z
               C Z
               B Y
               B Z
               A Y
               C Z
               C Z
               C Y
               A Y
               C Z
               C Z
               B Y
               A Z
               A Y
               C Z
               C Z
               B Y
               C Z
               B Y
               B Z
               C X
               C Y
               C Z
               A Y
               C Z
               A Z
               A X
               B X
               C Z
               C Y
               C Z
               C X
               B X
               B Y
               B Y
               C Z
               C Z
               C Z
               A X
               B Z
               C Z
               A Z
               A Z
               C Z
               B Y
               B X
               B Y
               C Z
               B Z
               C Z
               B X
               B Z
               C Z
               B X
               A X
               C Z
               C X
               B Z
               C Y
               C X
               C Z
               C X
               A X
               A X
               C Z
               C Z
               C Z
               B X
               B X
               C Z
               C Z
               C X
               C X
               C Z
               A Y
               B Y
               B Y
               B Y
               C Z
               C Y
               C Z
               C Z
               C Z
               B Y
               C Y
               C Z
               B X
               C Z
               A X
               C Y
               A Y
               C X
               A Y
               A Z
               C Z
               B Y
               B Y
               A Z
               C Y
               B Z
               B Z
               A X
               B Y
               C Z
               B X
               A Z
               A Z
               C Z
               B Z
               A Z
               C X
               B Z
               C Z
               C Z
               C Z
               C Z
               B X
               B Y
               C Z
               C Z
               C X
               C Y
               A Z
               B X
               B Y
               B Z
               C Z
               B Z
               C Z
               C Z
               C Z
               C Z
               A Y
               C X
               C Z
               A Y
               C Z
               C Z
               B Z
               C Z
               A Z
               C Z
               A Y
               C X
               C Z
               A X
               C X
               C Z
               C Z
               B Y
               C Z
               A Z
               C X
               C Z
               B Y
               A Y
               B Y
               C Z
               B X
               A X
               C Z
               B Y
               C Z
               B Y
               A Z
               A Z
               C Z
               A Z
               B Y
               C Z
               C Y
               B X
               C Z
               A Z
               B Z
               C Z
               C Y
               C Z
               B Z
               A X
               A X
               A Z
               C Z
               C Z
               C Y
               C X
               C X
               A X
               C X
               B X
               C X
               A Y
               C Y
               C Z
               C Z
               C Z
               C Z
               C X
               A Y
               C Y
               A Y
               B X
               C Y
               C Z
               A X
               A Z
               C Z
               C Z
               B Y
               C Z
               B Z
               C Z
               C Z
               A Y
               A Y
               C Z
               C Z
               A Z
               C Z
               C Z
               B X
               C Y
               C Z
               C Z
               C Z
               C Z
               A X
               B Y
               B X
               B Z
               C Z
               A Z
               A Z
               B Z
               A Z
               B X
               C Z
               B Z
               C Z
               A Z
               C Z
               C Z
               A Y
               B Y
               C Y
               B X
               A Z
               C X
               C Z
               C X
               B Y
               B Z
               C Z
               C Z
               C Z
               C Y
               C Z
               A X
               A X
               A Y
               C X
               C X
               A Y
               B Y
               C X
               C Z
               C Z
               B X
               B Z
               B X
               C X
               B X
               A Y
               C Z
               A Z
               C Z
               C Z
               C Z
               C Z
               C X
               A Z
               B Y
               C Z
               C X
               A Y
               A Y
               C Z
               C Z
               B Z
               B X
               C Z
               A Z
               B Y
               C Z
               C Z
               B Y
               A Y
               C Z
               B Z
               B Z
               A Z
               C X
               C Z
               B Z
               C Z
               C Z
               B Y
               C X
               B Y
               A Z
               C Z
               A X
               C Z
               B Y
               C Z
               A Z
               B Z
               C Z
               A Z
               A Y
               C Y
               B X
               C Z
               A Y
               C Y
               A X
               A Z
               A Y
               C X
               C Z
               C Z
               B Z
               A Z
               C Z
               C Z
               C Y
               C X
               C Y
               B Y
               C Z
               B Y
               C Y
               C Y
               C Y
               A X
               C Z
               C Z
               B X
               B Y
               C Z
               A Y
               C Z
               A Y
               B Z
               C Z
               C Z
               C Z
               A Y
               A X
               B Z
               B Y
               A Y
               A Y
               B Y
               B Z
               C X
               A Y
               B Y
               C X
               C Z
               C Z
               B Y
               C Z
               C X
               C Z
               C X
               C Z
               A Y
               A Y
               B Y
               C Z
               A Z
               C Y
               C Z
               A X
               C Y
               C Y
               C Y
               A Z
               C X
               C Z
               C Z
               A Z
               C Z
               B Y
               C Y
               C Z
               C Z
               C Z
               B Z
               C X
               C Z
               C Z
               C X
               C Z
               C Z
               C X
               C Z
               C X
               B Z
               B X
               A X
               C Z
               A Y
               C Z
               B X
               C Y
               A X
               C X
               B Z
               C Z
               A Y
               A X
               C X
               B Z
               B Z
               C X
               A Y
               C Y
               A Y
               C Z
               C Y
               A X
               C Z
               A Y
               A Z
               C Z
               B Y
               C X
               A Y
               A Y
               C Y
               B Y
               A Z
               B Y
               C X
               A Y
               B Z
               B Z
               C Z
               C Y
               C Z
               B Y
               C X
               C Z
               C Z
               A Y
               C Z
               C X
               A Y
               C Z
               C Z
               B X
               C Z
               A X
               C Z
               A Y
               C Y
               A Y
               B X
               C Y
               C Y
               A Y
               C Z
               A Z
               C Z
               C Y
               C Z
               A Z
               A Z
               C Z
               C Z
               C Z
               C Z
               C Z
               A Y
               A Z
               B Y
               C Z
               A Y
               C Y
               C Z
               A Y
               C X
               C Z
               A Z
               C Z
               C Y
               C X
               C Z
               C Y
               A X
               B Y
               C Z
               A Y
               A Z
               C X
               C X
               C Z
               A Z
               C Z
               C Z
               C Z
               C Z
               A X
               C Z
               C Z
               C X
               C Z
               A Y
               C Z
               C Z
               B X
               B Y
               C Y
               B Z
               C Y
               C Z
               B Y
               A Y
               A Y
               B Y
               A Z
               B Z
               B Y
               A X
               C Z
               B X
               A Y
               C X
               C Z
               C X
               C Z
               C Z
               C X
               A Z
               B Y
               A X
               C Z
               C Z
               B Z
               C X
               C X
               B Z
               A Y
               A Y
               A Y
               A Z
               C Y
               C Z
               A X
               B Y
               C Z
               B Y
               B Y
               C Y
               C Z
               C Y
               B Y
               C Z
               B Z
               C X
               C X
               A X
               C Z
               C Z
               B Z
               A Y
               A Z
               B X
               B Z
               B Y
               C Z
               A Z
               C X
               A Z
               B Y
               C Z
               B Y
               A Y
               C Z
               A Y
               B Z
               C Z
               A Z
               B Z
               B Y
               B Y
               A X
               B Y
               B Y
               C Z
               B Y
               C Z
               B Z
               A Z
               A Y
               C Z
               B Y
               C Z
               C Z
               C X
               C X
               C Y
               B Y
               C Y
               A Z
               C Z
               A Z
               C Z
               B Z
               C Y
               C Z
               A X
               B X
               A Z
               A Y
               A Y
               C Z
               C Z
               C Z
               C Y
               C Z
               C Z
               A Z
               A X
               B X
               A Z
               C Y
               C Z
               B Y
               A Y
               A Y
               B X
               B X
               C Z
               C Z
               C Z
               C X
               C Z
               C Y
               C Z
               A Y
               C Z
               C Z
               C Y
               A Z
               B Y
               A Y
               B Y
               B Y
               A Y
               A Y
               B Z
               C Z
               C X
               B Y
               C Z
               C Z
               C X
               A Z
               B Y
               A Z
               C Z
               C Z
               B Y
               C X
               C Z
               C Y
               A Y
               C Z
               A Y
               B Y
               A Y
               C X
               C Y
               C Y
               B Y
               B Z
               A Z
               C Z
               C Y
               B Z
               B Y
               A Y
               A Z
               A Y
               A Y
               B X
               C Z
               A X
               B Y
               B Y
               C Z
               B Y
               B Y
               B Z
               C Z
               A Y
               C X
               A X
               A Y
               C X
               A Y
               A Z
               C Z
               B Y
               B Y
               B Y
               C Y
               A Y
               B Z
               C Z
               C Z
               B Z
               C Z
               B X
               C Y
               B Y
               A Z
               C X
               A Z
               C Z
               B X
               C Z
               C Z
               B Z
               C Z
               A Z
               A Z
               B Y
               C Z
               A Z
               C Y
               B Y
               B Z
               C Z
               C X
               C Z
               A Z
               C Z
               C Y
               C X
               A Y
               B Y
               B X
               C X
               C Z
               A Z
               C X
               B Z
               C Z
               A Y
               C Y
               C Z
               A Z
               C Z
               A Z
               C Y
               C X
               C Y
               B Z
               B Y
               A Z
               A Y
               B X
               A Z
               C X
               C Y
               C X
               C Z
               C X
               A X
               C Z
               B Y
               C Z
               A Y
               B Z
               C X
               B Y
               C Z
               A Z
               C Z
               C Z
               C Y
               A Y
               A Z
               A Y
               C X
               B Z
               A Z
               C Z
               C Z
               C Z
               A X
               C Z
               A Z
               A Y
               C X
               B X
               C Z
               C Z
               A X
               A Y
               C Z
               C X
               C Z
               A Z
               C Y
               C Z
               B Z
               C Y
               C X
               A Y
               A X
               A Z
               C Z
               C Z
               C Z
               C Z
               A Y
               C Z
               A Z
               A Y
               C Z
               B Z
               B Y
               C X
               C Z
               C X
               C Z
               B X
               A Y
               C Z
               B Z
               A Z
               A Z
               B Z
               B Z
               C Z
               C Z
               B Y
               C Z
               A Y
               C X
               A X
               A X
               C X
               C X
               B Y
               B X
               A Y
               C Z
               B X
               B Y
               A Z
               B Z
               A Z
               A Z
               C X
               C Z
               A X
               A Y
               C X
               C Y
               C Y
               C X
               A Z
               C Z
               C X
               C X
               A Y
               A X
               C Z
               C Z
               B Y
               B Z
               C X
               C X
               C Z
               B Z
               B Z
               B Z
               B Z
               B Y
               B X
               C Z
               C Z
               C Z
               C X
               C Z
               C Z
               B Y
               C Z
               C X
               B Y
               C Z
               C Y
               B Z
               C Y
               C Z
               C Z
               C Z
               C Z
               C Z
               C Z
               C Z
               A X
               A Y
               C Y
               C Z
               A Y
               B X
               C Z
               B Y
               C Y
               C Z
               C Z
               C Z
               C Y
               C Z
               A Z
               B Y
               A Z
               C Z
               B Z
               C X
               C X
               A Z
               C Z
               C X
               C Z
               B Z
               C Z
               C Y
               B X
               C Z
               A Z
               C X
               B Y
               B Y
               C Z
               C Z
               C Z
               B Y
               C Z
               B Y
               A Y
               B Z
               B Z
               B Y
               C Z
               B Z
               A X
               C Z
               C Z
               C Z
               B Y
               B Y
               C Z
               C Y
               C Z
               B Y
               C Z
               B X
               B Z
               C X
               B Y
               C Y
               B Y
               C Z
               A Y
               B Z
               C X
               B Y
               A Z
               C Z
               C X
               A Z
               B Z
               A Y
               C Z
               C X
               B Y
               C Z
               C Z
               B Y
               B Z
               C X
               C X
               C Z
               C Z
               C X
               B Z
               A Y
               C Z
               C X
               A Z
               C Z
               C Z
               C Z
               C Y
               B Z
               A X
               B Z
               B Z
               C Z
               C Z
               B Z
               C Z
               B Z
               A X
               B Z
               B Y
               B Z
               B Z
               B Y
               C X
               A Y
               B Y
               B X
               B X
               A X
               C Z
               C Y
               C Y
               C Y
               C Y
               B Y
               A X
               C Y
               A X
               C Z
               B Z
               C Z
               C Y
               B Y
               A Z
               C Y
               A Z
               B Y
               B X
               C Z
               A X
               A Z
               C Z
               C Z
               A X
               C Z
               C X
               A Z
               C Y
               B Z
               C Y
               B Z
               A Y
               A Z
               C Z
               A Y
               C Z
               C Z
               A X
               C Z
               C Z
               C Z
               B Y
               C X
               C Y
               C Z
               B X
               A Z
               C Z
               C X
               B Y
               A Y
               B Y
               C Z
               C Z
               C Z
               A Y
               A X
               C Z
               C Z
               C Z
               C Z
               B Y
               A Z
               C Z
               A X
               A Y
               B Z"""
}
